llm_configs:
  "model": "chat_model"
  "openai_api_key": "token-abc123"
  "openai_api_base": "http://localhost:5532/v1"
  "temperature": 0.6
  "top_p": 0.9
  "max_tokens": 4096

tts_configs:
  "api_key": ""
  "api_base": "http://localhost:8080/v1"

asr_configs:
  "api_key": "token-abc123"
  "api_base": "http://localhost:5500/v1"
  "model": "openai/whisper-large-v3"
  "language": "ko"
  "temperature": 0.0
  "response_format": "json"