version: '3'
services:
  chatbot-website:
    build: ./chatbot-website
    ports:
      - "3000:3000"
    # depends_on:
    #   - chatbot-api
    #   - tts-api

  # chatbot-api:
  #   build: ./chatbot-api
  #   ports:
  #     - "5001:5001"

  # tts-api:
  #   build: ./tts-api
  #   ports:
  #     - "5002:5002"