# Use the official Python image from the Docker Hub
FROM python:3.10.14-slim-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose the port that the app runs on
EXPOSE 8201

# Command to run the application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8201"]