address:
  chat_model: spow12/ChatWaifu_v1.2.1
  llm_api_url: http://vllm-openai:8000/v1
  tts_api_url: http://tts:7860/api
  asr_api_url: http://faster-whsiper-server:8002/v1
  api_key: token-abc123

db:
  db_path: /app/chromadb/visual_novel/data
  collection_name: chat_db_storage

tts_configs:
  sr: 16000
  model: 'visual_novel'
  modelFile: model_assets/visual_novel/visual_novel_e56_s50000.safetensors
