address:
  emb_model: pkshatech/GLuCoSE-base-ja
  chat_model: spow12/ChatWaifu_v1.0
  llm_api_url: http://vllm-openai:8000/v1
  llm_api_key: token-abc123

db:
  db_path: /app/chromadb/visual_novel/data
  collection_name: chat_RAG_GLuCoSE-base-ja

generation_configs:
  temperature: 0.5
  top_p: 0.95